export const data = [
    {
      question: "What is the purpose of the __init__ method in Python classes?",
      option1: "Initialization method",
      option2: " Destructor method",
      option3: "Private method",
      option4: "Static method",
      ans: 1,
    },
    {
      question: "In Python, how do you create an empty list?",
      option1: "list()",        
      option2: "[]",
      option3: "emptyList()",
      option4: "None of the above",
      ans: 2,
    },
    {
      question: "Which of the following is a mutable data type in Python?",
      option1: "Tuple",
      option2: "String",
      option3: "List",
      option4: "Set",
      ans: 3,
    },
    {
      question: "How do you define a function in Python",
      option1: "func myFunction():",
      option2: "function myFunction():",
      option3: "def myFunction():",
      option4: "define myFunction():",
      ans: 3,
    },
    {
      question: "What is the purpose of the break statement in Python?",
      option1: "Terminate the loop",
      option2: "Skip the current iteration",
      option3: "Continue to the next iteration",
      option4: "Exit the program",
      ans: 1,
    },
    {
      question: "Which statement is used for making decisions in Python?",
      option1: "switch",
      option2: "if",
      option3: "select",
      option4: "choose",
      ans: 2,
    },
    {
      question: "What does the 'self' keyword represent in a class method?",
      option1: "Current instance of the class",
      option2: "Parent class instance",
      option3: "Global instance",
      option4: "Class object",
      ans: 1,
    },
    {
      question: "Which of the following is not a valid Python variable name?",
      option1: "my_var",
      option2: "123_var",
      option3: " _var",
      option4: "var123",
      ans: 2,
    },
    {
      question: "How do you open a file in Python for reading?",
      option1: 'open("file.txt", "r")',
      option2: 'read("file.txt")',
      option3: 'fopen("file.txt", "read")',
      option4: 'file("file.txt", "read")',
      ans: 1,
    },
    {
      question: "What is the output of 2 * 3 ** 2 in Python?",
      option1: " 18",
      option2: "36",
      option3: " 12",
      option4: "27",
      ans: 2,
    },
  ];